<a href="https://colab.research.google.com/github/Dima200206/-2/blob/main/%D0%9B%D0%911_%D0%92%D0%BB%D0%B0%D1%81%D0%B5%D0%BD%D0%BA%D0%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ЛБ 1

In [1]:
# Завдання 1
import numpy as np

# Створення одновимірного масиву зі зворотним порядком перших 10 натуральних чисел
vector = np.arange(1, 11)[::-1]
print(vector)

[10  9  8  7  6  5  4  3  2  1]


In [2]:
# Завдання 2
import numpy as np

# Створення двовимірного масиву (матриці) розміром 3x3
# Початкове значення - 27, далі зменшуємо на 3
matrix = np.arange(27, 0, -3).reshape(3, 3)
print(matrix)


[[27 24 21]
 [18 15 12]
 [ 9  6  3]]


In [4]:
# Завдання 3
import numpy as np

# Створення масиву розміром 3x3, заповненого випадковими дійсними числами від 0 до 1
random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.75213433 0.02761326 0.56259167]
 [0.51967966 0.64526081 0.89813996]
 [0.14607042 0.0368468  0.71272928]]


In [5]:
# Завдання 4
import numpy as np

# Створення масиву розміром 3x3, заповненого випадковими дійсними числами від 0 до 1
random_matrix = np.random.rand(3, 3)

# Обчислення добутку всіх елементів масиву
product_of_elements = np.prod(random_matrix)

print("Масив:")
print(random_matrix)
print("\nДобуток всіх елементів масиву:")
print(product_of_elements)


Масив:
[[0.33522961 0.24327281 0.98252746]
 [0.85049869 0.20887226 0.18126496]
 [0.9518677  0.40510909 0.2070228 ]]

Добуток всіх елементів масиву:
0.0002059755436727186


In [6]:
# Завдання 5
import numpy as np

# Створення двох одновимірних масивів розміром 6, заповнених випадковими цілими числами від -20 до 20
array1 = np.random.randint(-20, 21, 6)
array2 = np.random.randint(-20, 21, 6)

# Поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("\nДодавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Масив 1: [11 13 -3  1  0 -3]
Масив 2: [10  7 16 -7 17 -4]

Додавання: [21 20 13 -6 17 -7]
Віднімання: [  1   6 -19   8 -17   1]
Множення: [110  91 -48  -7   0  12]


In [7]:
# Завдання 6
import numpy as np

# Створення двох матриць розміром 2x2, заповнених довільними цілими числами від 6 до 10
matrix1 = np.random.randint(6, 11, (2, 2))
matrix2 = np.random.randint(6, 11, (2, 2))

# Обчислення добутку матриць
matrix_product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nДобуток матриць:")
print(matrix_product)

Матриця 1:
[[8 9]
 [9 6]]

Матриця 2:
[[9 9]
 [6 9]]

Добуток матриць:
[[126 153]
 [117 135]]


In [8]:
# Завдання 7
import numpy as np

# Створення матриці розміром 3x2, заповненої випадковими цілими числами від 1 до 8
matrix1 = np.random.randint(1, 9, (3, 2))

# Створення матриці розміром 2x2, заповненої випадковими цілими числами від 1 до 8
matrix2 = np.random.randint(1, 9, (2, 2))

# Перемноження матриць
matrix_product = np.dot(matrix1, matrix2)

print("Матриця 1 (3x2):")
print(matrix1)
print("\nМатриця 2 (2x2):")
print(matrix2)
print("\nДобуток матриць (3x2) * (2x2):")
print(matrix_product)


Матриця 1 (3x2):
[[2 7]
 [2 1]
 [8 4]]

Матриця 2 (2x2):
[[6 7]
 [4 2]]

Добуток матриць (3x2) * (2x2):
[[40 28]
 [16 16]
 [64 64]]


In [9]:
# Завдання 8
import numpy as np

# Створення матриці розміром 2x2, заповненої випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (2, 2))

# Обчислення оберненої матриці
inverse_matrix = np.linalg.inv(matrix)

print("Матриця:")
print(matrix)
print("\nОбернена матриця:")
print(inverse_matrix)


Матриця:
[[8 8]
 [5 2]]

Обернена матриця:
[[-0.08333333  0.33333333]
 [ 0.20833333 -0.33333333]]


In [10]:
# Завдання 9
import numpy as np

# Створення матриці розміром 3x3, заповненої випадковими цілими числами від 0 до 1
matrix = np.random.randint(0, 2, (3, 3))

# Транспонування матриці
transposed_matrix = matrix.T

print("Оригінальна матриця:")
print(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)


Оригінальна матриця:
[[0 0 0]
 [1 0 1]
 [0 1 1]]

Транспонована матриця:
[[0 1 0]
 [0 0 1]
 [0 1 1]]


In [11]:
# Завдання 10
import numpy as np

# Створення матриці розміром 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)

# Створення вектора розміром 4x1 з випадковими цілими числами в діапазоні від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))

# Обчислення добутку матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)


Матриця:
[[0.36841997 0.90332565 0.56738936 0.59950427]
 [0.36317239 0.75672928 0.8865751  0.75705451]
 [0.88290484 0.116495   0.05708419 0.868171  ]]

Вектор:
[[9]
 [2]
 [7]
 [4]]

Добуток матриці на вектор:
[[11.49217363]
 [14.01625377]
 [12.0514069 ]]


In [12]:
# Завдання 11
import numpy as np

# Створення матриці розміром 2x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(2, 3))

# Створення вектора розміром 3x1 з випадковими цілими числами в діапазоні від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Обчислення добутку матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)


Матриця:
[[4 5 7]
 [4 6 3]]

Вектор:
[[1]
 [3]
 [2]]

Добуток матриці на вектор:
[[33]
 [28]]


In [13]:
# Завдання 12
import numpy as np

# Створення двох матриць розміром 6x6 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(6, 6))
matrix2 = np.random.randint(1, 11, size=(6, 6))

# Обчислення суми двох матриць
matrix_sum = matrix1 + matrix2

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nСума матриць:")
print(matrix_sum)


Перша матриця:
[[ 6  4  3  3  2  4]
 [ 7  8  2  3  7  1]
 [ 6  1  7  4  7  3]
 [ 6  4  9  5  9  2]
 [ 2  9  2 10  9  2]
 [ 1  5  6  5  9  2]]

Друга матриця:
[[ 9  2  5  4  4  8]
 [ 8  6  4  8  7  6]
 [10  6  8  9 10  1]
 [ 5  6  6  7  5 10]
 [ 7  6  3  9  9  5]
 [ 3 10  5  6  4  4]]

Сума матриць:
[[15  6  8  7  6 12]
 [15 14  6 11 14  7]
 [16  7 15 13 17  4]
 [11 10 15 12 14 12]
 [ 9 15  5 19 18  7]
 [ 4 15 11 11 13  6]]


In [14]:
# Завдання 13
import numpy as np

# Створення двох матриць розміром 6x6 з випадковими дійсними числами від 0 до 1
matrix1 = np.random.rand(6, 6)
matrix2 = np.random.rand(6, 6)

# Обчислення різниці між елементами двох матриць
matrix_difference = matrix1 - matrix2

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nРізниця матриць:")
print(matrix_difference)


Перша матриця:
[[0.05911822 0.99819007 0.36195959 0.99613126 0.10917263 0.87903892]
 [0.74256853 0.82795737 0.06315557 0.8773127  0.04015507 0.21391026]
 [0.09661315 0.67869122 0.55542086 0.78247394 0.86501903 0.76975174]
 [0.31683847 0.1095511  0.74463603 0.57032983 0.04102827 0.30747206]
 [0.13385078 0.83854998 0.47438554 0.89446361 0.27039637 0.98225071]
 [0.63341733 0.21009309 0.01028876 0.42097691 0.58735078 0.5187704 ]]

Друга матриця:
[[0.73622646 0.92941322 0.82810907 0.82413402 0.98147497 0.40780273]
 [0.12583134 0.06672392 0.84169048 0.04688028 0.80149031 0.96148974]
 [0.28513117 0.92707257 0.89081687 0.03634112 0.98168534 0.08594508]
 [0.83637714 0.71646632 0.12342786 0.63628442 0.93098712 0.4859205 ]
 [0.92785645 0.69958275 0.75215273 0.73500144 0.42069447 0.38479619]
 [0.90746102 0.48046834 0.13631568 0.16320737 0.41666984 0.49070687]]

Різниця матриць:
[[-0.67710825  0.06877685 -0.46614947  0.17199723 -0.87230234  0.47123619]
 [ 0.61673719  0.76123345 -0.77853491  0.83043

In [15]:
# Завдання 14
import numpy as np

# Створення матриці розміром 3x3 з випадковими дійсними числами в діапазоні від -5 до 5
matrix = np.random.uniform(-5, 5, size=(3, 3))

# Обчислення добутку всіх елементів матриці
product = np.prod(matrix)

print("Матриця:")
print(matrix)
print("\nДобуток елементів матриці:")
print(product)


Матриця:
[[-0.88627277 -3.42079938 -1.66376265]
 [ 0.65796661  3.78615751  1.53693785]
 [-4.83835773 -3.05402906  1.71878362]]

Добуток елементів матриці:
-490.4983624288821


In [16]:
# Завдання 15
import numpy as np

# Створення матриці розміром 7x7 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(7, 7)

# Знаходження індексу найбільшого елемента в кожному рядку
max_indices = np.argmax(matrix, axis=1)

# Формування вектора-стовпчика, що містить найбільші елементи з кожного рядка
max_values = matrix[np.arange(matrix.shape[0]), max_indices]

# Перетворення вектора значень у вектор-стовпчик
max_values_column_vector = max_values.reshape(-1, 1)

print("Матриця:")
print(matrix)
print("\nВектор-стовпчик, що містить найбільші елементи в кожному рядку:")
print(max_values_column_vector)


Матриця:
[[0.89997793 0.18225371 0.26341585 0.72349669 0.14782903 0.56691349
  0.7415571 ]
 [0.36198095 0.83572891 0.60370707 0.03042769 0.33723405 0.33723398
  0.60232814]
 [0.34808646 0.35984741 0.33180432 0.20503585 0.07989756 0.12643633
  0.39888454]
 [0.67793453 0.7586551  0.05778686 0.20523425 0.11385428 0.70632879
  0.9266758 ]
 [0.25276748 0.35109292 0.28048282 0.97580051 0.98776553 0.83725859
  0.98445912]
 [0.04341971 0.78641346 0.81692489 0.48987747 0.97168979 0.09292079
  0.40431362]
 [0.95051269 0.98594565 0.70039643 0.18604027 0.29264237 0.4256863
  0.20079633]]

Вектор-стовпчик, що містить найбільші елементи в кожному рядку:
[[0.89997793]
 [0.83572891]
 [0.39888454]
 [0.9266758 ]
 [0.98776553]
 [0.97168979]
 [0.98594565]]
